<?php

namespace StasisMedia\OAuth\Request;

require_once __DIR__ . '/../../../../bootstrap.php';

use StasisMedia\OAuth\Parameter\Parameter;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2010-10-31 at 01:02:47.
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{

    /*
    public function testGetBaseString() {
        $request = new \StasisMedia\OAuth\Request\MockRequest(
            'http://example.com/request?b5=%3D%253D&a3=a&c%40=&a2=r%20b',
            'POST', false
        );
        
        $request->setPostParameters(Parameter::fromQueryString('c2&a3=2+q'));

        $request->setAuthorizationHeader('Authorization: OAuth realm="Example",
            oauth_consumer_key="9djdj82h48djs9d2",
            oauth_token="kkk9d7dh3k39sjv7",
            oauth_signature_method="HMAC-SHA1",
            oauth_timestamp="137131201",
            oauth_nonce="7d8f3e4a"');

        $this->assertEquals('POST&http%3A%2F%2Fexample.com%2Frequest&a2%3Dr%252'
                . '0b%26a3%3D2%2520q%26a3%3Da%26b5%3D%253D%25253D%26c%2540%3D%2'
                . '6c2%3D%26oauth_consumer_key%3D9djdj82h48djs9d2%26oauth_nonce'
                . '%3D7d8f3e4a%26oauth_signature_method%3DHMAC-SHA1%26oauth_tim'
                . 'estamp%3D137131201%26oauth_token%3Dkkk9d7dh3k39sjv7',
                $request->getBaseString());
    }
     * 
     */

}

?>
