<?php
namespace StasisMedia\OAuth\Parameter;

require_once __DIR__ . '/../../../../bootstrap.php';

/**
 * Test class for Parameter.
 * Generated by PHPUnit on 2010-10-30 at 17:39:32.
 */
class ParameterTest extends \PHPUnit_Framework_TestCase {

    public function testBasicNormalized() {
        $parameter = new Parameter('foo', 'bar');
        $this->assertEquals('foo=bar', $parameter->getNormalized());
    }

    /**
     * @dataProvider multipleNormalizedProvider
     */
    public function testMultipleNormalized($name, $value, $expected) {

        $parameter = new Parameter($name, $value);
        
        $this->assertEquals($expected, $parameter->getNormalized());
    }

    public function multipleNormalizedProvider()
    {
        return array(
            array('a3', array('a', '2 q'), 'a3=2%20q&a3=a'),
            array('a', array('x!y', 'x y'), 'a=x%20y&a=x%21y'),
            array('a', array('x y', 'x!y'), 'a=x%20y&a=x%21y'),
        );
    }
}

?>
